/**
 * PDF Export Service
 * Generates PDF reports from meeting sessions
 */

import jsPDF from 'jspdf';
import { MeetingSession, TranscriptSegment, MeetingActionItem } from './meeting-storage';

export interface PDFExportOptions {
  title?: string;
  includeTranscript: boolean;
  includeSummary: boolean;
  includeActionItems: boolean;
  language: 'es' | 'en' | 'pt';
  companyLogo?: string; // Base64 image
}

export interface PDFExportData {
  session: MeetingSession;
  transcript: TranscriptSegment[];
  actionItems?: MeetingActionItem[];
}

// Translations for PDF content
const translations = {
  es: {
    meetingTranscript: 'Transcripción de Reunión',
    summary: 'Resumen',
    transcript: 'Transcripción',
    actionItems: 'Acciones Pendientes',
    date: 'Fecha',
    duration: 'Duración',
    platform: 'Plataforma',
    participants: 'Participantes',
    generatedBy: 'Generado por Lia',
    page: 'Página',
    of: 'de',
    minutes: 'minutos',
    noSummary: 'No hay resumen disponible.',
    noTranscript: 'No hay transcripción disponible.',
    noActionItems: 'No hay acciones pendientes.',
    assignee: 'Responsable',
    dueDate: 'Fecha límite',
    status: 'Estado',
    pending: 'Pendiente',
    inProgress: 'En progreso',
    completed: 'Completado'
  },
  en: {
    meetingTranscript: 'Meeting Transcript',
    summary: 'Summary',
    transcript: 'Transcript',
    actionItems: 'Action Items',
    date: 'Date',
    duration: 'Duration',
    platform: 'Platform',
    participants: 'Participants',
    generatedBy: 'Generated by Lia',
    page: 'Page',
    of: 'of',
    minutes: 'minutes',
    noSummary: 'No summary available.',
    noTranscript: 'No transcript available.',
    noActionItems: 'No action items.',
    assignee: 'Assignee',
    dueDate: 'Due date',
    status: 'Status',
    pending: 'Pending',
    inProgress: 'In Progress',
    completed: 'Completed'
  },
  pt: {
    meetingTranscript: 'Transcrição da Reunião',
    summary: 'Resumo',
    transcript: 'Transcrição',
    actionItems: 'Ações Pendentes',
    date: 'Data',
    duration: 'Duração',
    platform: 'Plataforma',
    participants: 'Participantes',
    generatedBy: 'Gerado por Lia',
    page: 'Página',
    of: 'de',
    minutes: 'minutos',
    noSummary: 'Nenhum resumo disponível.',
    noTranscript: 'Nenhuma transcrição disponível.',
    noActionItems: 'Nenhuma ação pendente.',
    assignee: 'Responsável',
    dueDate: 'Data limite',
    status: 'Status',
    pending: 'Pendente',
    inProgress: 'Em andamento',
    completed: 'Concluído'
  }
};

export class PDFExportService {
  private doc: jsPDF | null = null;
  private currentY: number = 0;
  private pageNumber: number = 1;
  private t: typeof translations.es;
  private readonly margin = 20;
  private readonly pageWidth = 210; // A4 width in mm
  private readonly pageHeight = 297; // A4 height in mm
  private readonly contentWidth: number;
  private readonly lineHeight = 6;

  constructor(language: 'es' | 'en' | 'pt' = 'es') {
    this.t = translations[language];
    this.contentWidth = this.pageWidth - 2 * this.margin;
  }

  /**
   * Generate PDF from meeting data
   */
  async generateMeetingPDF(
    data: PDFExportData,
    options: PDFExportOptions
  ): Promise<Blob> {
    this.t = translations[options.language];
    this.doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    this.currentY = this.margin;
    this.pageNumber = 1;

    // Add header
    this.addHeader(data.session, options.title);

    // Add metadata
    this.addMetadata(data.session);

    // Add summary if included
    if (options.includeSummary && data.session.summary) {
      this.addSection(this.t.summary, data.session.summary);
    }

    // Add action items if included
    if (options.includeActionItems && data.actionItems && data.actionItems.length > 0) {
      this.addActionItems(data.actionItems);
    }

    // Add transcript if included
    if (options.includeTranscript && data.transcript.length > 0) {
      this.addTranscript(data.transcript);
    }

    // Add footer to all pages
    this.addFooterToAllPages();

    return this.doc.output('blob');
  }

  private addHeader(session: MeetingSession, customTitle?: string): void {
    if (!this.doc) return;

    // Title
    this.doc.setFontSize(20);
    this.doc.setFont('helvetica', 'bold');
    const title = customTitle || session.title || this.t.meetingTranscript;
    this.doc.text(title, this.margin, this.currentY);
    this.currentY += 12;

    // Subtitle with Lia branding
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(100, 100, 100);
    this.doc.text(this.t.generatedBy, this.margin, this.currentY);
    this.doc.setTextColor(0, 0, 0);
    this.currentY += 10;

    // Horizontal line
    this.doc.setDrawColor(200, 200, 200);
    this.doc.line(this.margin, this.currentY, this.pageWidth - this.margin, this.currentY);
    this.currentY += 8;
  }

  private addMetadata(session: MeetingSession): void {
    if (!this.doc) return;

    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');

    const metadata = [
      { label: this.t.date, value: new Date(session.start_time).toLocaleDateString() },
      {
        label: this.t.duration,
        value: session.duration_seconds
          ? `${Math.round(session.duration_seconds / 60)} ${this.t.minutes}`
          : '-'
      },
      { label: this.t.platform, value: session.platform === 'google-meet' ? 'Google Meet' : 'Zoom' },
      {
        label: this.t.participants,
        value: session.participants?.length > 0
          ? session.participants.join(', ')
          : `${session.participant_count} participante(s)`
      }
    ];

    for (const item of metadata) {
      this.doc.setFont('helvetica', 'bold');
      this.doc.text(`${item.label}: `, this.margin, this.currentY);
      const labelWidth = this.doc.getTextWidth(`${item.label}: `);

      this.doc.setFont('helvetica', 'normal');
      this.doc.text(item.value, this.margin + labelWidth, this.currentY);
      this.currentY += this.lineHeight;
    }

    this.currentY += 8;
  }

  private addSection(title: string, content: string): void {
    if (!this.doc) return;

    // Check if we need a new page
    this.checkPageBreak(30);

    // Section title
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(50, 50, 50);
    this.doc.text(title, this.margin, this.currentY);
    this.currentY += 8;

    // Section content
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(0, 0, 0);

    const lines = this.doc.splitTextToSize(content, this.contentWidth);
    for (const line of lines) {
      this.checkPageBreak(this.lineHeight);
      this.doc.text(line, this.margin, this.currentY);
      this.currentY += this.lineHeight;
    }

    this.currentY += 10;
  }

  private addActionItems(actionItems: MeetingActionItem[]): void {
    if (!this.doc) return;

    this.checkPageBreak(30);

    // Section title
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(50, 50, 50);
    this.doc.text(this.t.actionItems, this.margin, this.currentY);
    this.currentY += 8;

    this.doc.setFontSize(10);
    this.doc.setTextColor(0, 0, 0);

    for (const item of actionItems) {
      this.checkPageBreak(15);

      // Checkbox
      const checkbox = item.status === 'completed' ? '☑' : '☐';
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(checkbox, this.margin, this.currentY);

      // Description
      const descLines = this.doc.splitTextToSize(item.description, this.contentWidth - 10);
      this.doc.text(descLines[0], this.margin + 6, this.currentY);
      this.currentY += this.lineHeight;

      for (let i = 1; i < descLines.length; i++) {
        this.doc.text(descLines[i], this.margin + 6, this.currentY);
        this.currentY += this.lineHeight;
      }

      // Assignee and due date
      if (item.assignee || item.due_date) {
        this.doc.setFontSize(9);
        this.doc.setTextColor(100, 100, 100);
        let details = '';
        if (item.assignee) details += `${this.t.assignee}: ${item.assignee}`;
        if (item.due_date) {
          if (details) details += ' | ';
          details += `${this.t.dueDate}: ${new Date(item.due_date).toLocaleDateString()}`;
        }
        this.doc.text(details, this.margin + 6, this.currentY);
        this.doc.setTextColor(0, 0, 0);
        this.doc.setFontSize(10);
        this.currentY += this.lineHeight;
      }

      this.currentY += 2;
    }

    this.currentY += 8;
  }

  private addTranscript(transcript: TranscriptSegment[]): void {
    if (!this.doc) return;

    this.checkPageBreak(30);

    // Section title
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(50, 50, 50);
    this.doc.text(this.t.transcript, this.margin, this.currentY);
    this.currentY += 10;

    this.doc.setFontSize(9);
    this.doc.setTextColor(0, 0, 0);

    for (const segment of transcript) {
      this.checkPageBreak(15);

      // Time
      const time = new Date(segment.timestamp).toLocaleTimeString([], {
        hour: '2-digit',
        minute: '2-digit'
      });

      // Speaker
      let speaker = segment.speaker || 'Participante';
      if (segment.is_lia_response) {
        speaker = 'Lia';
        this.doc.setTextColor(75, 0, 130); // Purple for Lia
      }

      // Header line
      this.doc.setFont('helvetica', 'bold');
      this.doc.text(`[${time}] ${speaker}:`, this.margin, this.currentY);
      this.currentY += this.lineHeight - 1;

      // Text content
      this.doc.setFont('helvetica', 'normal');
      const lines = this.doc.splitTextToSize(segment.text, this.contentWidth);

      for (const line of lines) {
        this.checkPageBreak(this.lineHeight);
        this.doc.text(line, this.margin, this.currentY);
        this.currentY += this.lineHeight - 1;
      }

      this.doc.setTextColor(0, 0, 0);
      this.currentY += 4;
    }
  }

  private checkPageBreak(requiredSpace: number): void {
    if (!this.doc) return;

    if (this.currentY + requiredSpace > this.pageHeight - this.margin - 15) {
      this.doc.addPage();
      this.pageNumber++;
      this.currentY = this.margin;
    }
  }

  private addFooterToAllPages(): void {
    if (!this.doc) return;

    const totalPages = this.doc.getNumberOfPages();

    for (let i = 1; i <= totalPages; i++) {
      this.doc.setPage(i);
      this.doc.setFontSize(8);
      this.doc.setTextColor(150, 150, 150);

      // Page number
      const pageText = `${this.t.page} ${i} ${this.t.of} ${totalPages}`;
      const pageTextWidth = this.doc.getTextWidth(pageText);
      this.doc.text(
        pageText,
        (this.pageWidth - pageTextWidth) / 2,
        this.pageHeight - 10
      );

      // Generated by Lia
      this.doc.text(
        this.t.generatedBy,
        this.margin,
        this.pageHeight - 10
      );

      // Date
      const dateText = new Date().toLocaleDateString();
      const dateTextWidth = this.doc.getTextWidth(dateText);
      this.doc.text(
        dateText,
        this.pageWidth - this.margin - dateTextWidth,
        this.pageHeight - 10
      );
    }

    this.doc.setTextColor(0, 0, 0);
  }

  /**
   * Download the PDF
   */
  static downloadPDF(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Generate filename for meeting PDF
   */
  static generateFilename(session: MeetingSession): string {
    const date = new Date(session.start_time);
    const dateStr = date.toISOString().split('T')[0];
    const title = session.title?.replace(/[^a-zA-Z0-9]/g, '_') || 'reunion';
    return `Lia_${title}_${dateStr}.pdf`;
  }
}

export default PDFExportService;
