-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_moderation_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  config_key text NOT NULL UNIQUE,
  config_value text NOT NULL,
  description text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  CONSTRAINT ai_moderation_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_moderation_logs (
  log_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['post'::text, 'comment'::text, 'other'::text])),
  content_id uuid,
  content_text text NOT NULL,
  is_flagged boolean NOT NULL DEFAULT false,
  confidence_score numeric,
  categories jsonb,
  reasoning text,
  model_used text,
  api_response jsonb,
  processing_time_ms integer,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'under_review'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_moderation_logs_pkey PRIMARY KEY (log_id),
  CONSTRAINT ai_moderation_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  admin_user_id uuid NOT NULL,
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['CREATE'::character varying::text, 'UPDATE'::character varying::text, 'DELETE'::character varying::text, 'VIEW'::character varying::text])),
  table_name character varying NOT NULL,
  record_id uuid NOT NULL,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES public.users(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.bulk_invite_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  created_by uuid,
  token character varying NOT NULL UNIQUE,
  name character varying,
  max_uses integer NOT NULL DEFAULT 100,
  current_uses integer NOT NULL DEFAULT 0,
  role character varying NOT NULL DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['member'::character varying, 'admin'::character varying, 'owner'::character varying]::text[])),
  expires_at timestamp with time zone NOT NULL,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'paused'::character varying, 'expired'::character varying, 'exhausted'::character varying]::text[])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bulk_invite_links_pkey PRIMARY KEY (id),
  CONSTRAINT bulk_invite_links_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT bulk_invite_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.bulk_invite_registrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bulk_invite_link_id uuid NOT NULL,
  user_id uuid NOT NULL,
  registered_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bulk_invite_registrations_pkey PRIMARY KEY (id),
  CONSTRAINT bulk_invite_registrations_bulk_invite_link_id_fkey FOREIGN KEY (bulk_invite_link_id) REFERENCES public.bulk_invite_links(id),
  CONSTRAINT bulk_invite_registrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.calendar_integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider text NOT NULL,
  access_token text,
  refresh_token text,
  expires_at timestamp with time zone,
  scope text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT calendar_integrations_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_integrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.calendar_subscription_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  token uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone,
  usage_count integer DEFAULT 0,
  CONSTRAINT calendar_subscription_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_subscription_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.calendar_sync_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  plan_id uuid,
  synced_at timestamp with time zone DEFAULT now(),
  events_snapshot jsonb NOT NULL,
  changes_detected jsonb,
  lia_notification_sent boolean DEFAULT false,
  notification_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calendar_sync_history_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_sync_history_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.study_plans(id),
  CONSTRAINT calendar_sync_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.certificate_ledger (
  block_id bigint NOT NULL DEFAULT nextval('certificate_ledger_block_id_seq'::regclass),
  cert_id uuid NOT NULL,
  op text NOT NULL CHECK (op = ANY (ARRAY['ISSUE'::text, 'REVOKE'::text, 'EXPIRE'::text])),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  prev_hash character,
  block_hash character NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT certificate_ledger_pkey PRIMARY KEY (block_id)
);
CREATE TABLE public.certificate_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  design_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT certificate_templates_pkey PRIMARY KEY (id),
  CONSTRAINT certificate_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.content_translations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['course'::text, 'module'::text, 'lesson'::text, 'activity'::text, 'material'::text, 'community'::text, 'news'::text])),
  entity_id uuid NOT NULL,
  language_code text NOT NULL CHECK (language_code = ANY (ARRAY['es'::text, 'en'::text, 'pt'::text, 'fr'::text, 'de'::text, 'it'::text, 'zh'::text, 'ja'::text, 'ko'::text])),
  translations jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT content_translations_pkey PRIMARY KEY (id),
  CONSTRAINT content_translations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.course_lessons (
  lesson_id uuid NOT NULL DEFAULT gen_random_uuid(),
  lesson_title character varying NOT NULL,
  lesson_description text,
  lesson_order_index integer NOT NULL DEFAULT 1 CHECK (lesson_order_index > 0),
  video_provider_id text NOT NULL,
  video_provider character varying NOT NULL CHECK (video_provider::text = ANY (ARRAY['youtube'::character varying::text, 'vimeo'::character varying::text, 'direct'::character varying::text, 'custom'::character varying::text])),
  duration_seconds integer NOT NULL CHECK (duration_seconds > 0),
  transcript_content text,
  is_published boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  module_id uuid NOT NULL,
  instructor_id uuid NOT NULL,
  summary_content text,
  total_duration_minutes integer DEFAULT 0,
  CONSTRAINT course_lessons_pkey PRIMARY KEY (lesson_id),
  CONSTRAINT course_lessons_instructor_id_fkey FOREIGN KEY (instructor_id) REFERENCES public.users(id),
  CONSTRAINT course_lessons_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.course_modules(module_id)
);
CREATE TABLE public.course_lessons_en (
  lesson_id uuid NOT NULL DEFAULT gen_random_uuid(),
  lesson_title character varying NOT NULL,
  lesson_description text,
  lesson_order_index integer NOT NULL DEFAULT 1 CHECK (lesson_order_index > 0),
  video_provider_id text NOT NULL,
  video_provider character varying NOT NULL CHECK (video_provider::text = ANY (ARRAY['youtube'::character varying::text, 'vimeo'::character varying::text, 'direct'::character varying::text, 'custom'::character varying::text])),
  duration_seconds integer NOT NULL CHECK (duration_seconds > 0),
  transcript_content text,
  is_published boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  module_id uuid NOT NULL,
  instructor_id uuid NOT NULL,
  summary_content text,
  CONSTRAINT course_lessons_en_pkey PRIMARY KEY (lesson_id),
  CONSTRAINT course_lessons_en_instructor_id_fkey FOREIGN KEY (instructor_id) REFERENCES public.users(id),
  CONSTRAINT course_lessons_en_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.course_modules(module_id)
);
CREATE TABLE public.course_lessons_pt (
  lesson_id uuid NOT NULL DEFAULT gen_random_uuid(),
  lesson_title character varying NOT NULL,
  lesson_description text,
  lesson_order_index integer NOT NULL DEFAULT 1 CHECK (lesson_order_index > 0),
  video_provider_id text NOT NULL,
  video_provider character varying NOT NULL CHECK (video_provider::text = ANY (ARRAY['youtube'::character varying::text, 'vimeo'::character varying::text, 'direct'::character varying::text, 'custom'::character varying::text])),
  duration_seconds integer NOT NULL CHECK (duration_seconds > 0),
  transcript_content text,
  is_published boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  module_id uuid NOT NULL,
  instructor_id uuid NOT NULL,
  summary_content text,
  CONSTRAINT course_lessons_pt_pkey PRIMARY KEY (lesson_id),
  CONSTRAINT course_lessons_pt_instructor_id_fkey FOREIGN KEY (instructor_id) REFERENCES public.users(id),
  CONSTRAINT course_lessons_pt_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.course_modules(module_id)
);
CREATE TABLE public.course_modules (
  module_id uuid NOT NULL DEFAULT gen_random_uuid(),
  module_title character varying NOT NULL,
  module_description text,
  module_order_index integer NOT NULL DEFAULT 1 CHECK (module_order_index > 0),
  module_duration_minutes integer DEFAULT 0 CHECK (module_duration_minutes >= 0),
  is_required boolean DEFAULT true,
  is_published boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  course_id uuid NOT NULL,
  CONSTRAINT course_modules_pkey PRIMARY KEY (module_id),
  CONSTRAINT course_modules_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.course_question_reactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  question_id uuid,
  response_id uuid,
  reaction_type text NOT NULL DEFAULT 'like'::text CHECK (reaction_type = ANY (ARRAY['like'::text, 'helpful'::text, 'love'::text, 'laugh'::text, 'thanks'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT course_question_reactions_pkey PRIMARY KEY (id),
  CONSTRAINT course_question_reactions_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.course_questions(id),
  CONSTRAINT course_question_reactions_response_id_fkey FOREIGN KEY (response_id) REFERENCES public.course_question_responses(id),
  CONSTRAINT course_question_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.course_question_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  question_id uuid NOT NULL,
  course_id uuid NOT NULL,
  user_id uuid NOT NULL,
  content text NOT NULL CHECK (length(TRIM(BOTH FROM content)) > 0),
  parent_response_id uuid,
  reaction_count integer DEFAULT 0 CHECK (reaction_count >= 0),
  reply_count integer DEFAULT 0 CHECK (reply_count >= 0),
  attachment_url text,
  attachment_type text CHECK (attachment_type IS NULL OR (attachment_type = ANY (ARRAY['image'::text, 'video'::text, 'document'::text, 'link'::text]))),
  attachment_data jsonb DEFAULT '{}'::jsonb,
  is_edited boolean DEFAULT false,
  edited_at timestamp with time zone,
  is_deleted boolean DEFAULT false,
  is_approved_answer boolean DEFAULT false,
  is_instructor_answer boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  organization_id uuid,
  CONSTRAINT course_question_responses_pkey PRIMARY KEY (id),
  CONSTRAINT course_question_responses_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT course_question_responses_parent_response_id_fkey FOREIGN KEY (parent_response_id) REFERENCES public.course_question_responses(id),
  CONSTRAINT course_question_responses_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.course_questions(id),
  CONSTRAINT course_question_responses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT course_question_responses_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.course_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid NOT NULL,
  user_id uuid NOT NULL,
  title text,
  content text NOT NULL CHECK (length(TRIM(BOTH FROM content)) > 0),
  view_count integer DEFAULT 0 CHECK (view_count >= 0),
  response_count integer DEFAULT 0 CHECK (response_count >= 0),
  reaction_count integer DEFAULT 0 CHECK (reaction_count >= 0),
  attachment_url text,
  attachment_type text CHECK (attachment_type IS NULL OR (attachment_type = ANY (ARRAY['image'::text, 'video'::text, 'document'::text, 'link'::text]))),
  attachment_data jsonb DEFAULT '{}'::jsonb,
  is_pinned boolean DEFAULT false,
  is_edited boolean DEFAULT false,
  edited_at timestamp with time zone,
  is_hidden boolean DEFAULT false,
  is_resolved boolean DEFAULT false,
  tags ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  organization_id uuid,
  CONSTRAINT course_questions_pkey PRIMARY KEY (id),
  CONSTRAINT course_questions_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT course_questions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT course_questions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.course_reviews (
  review_id uuid NOT NULL DEFAULT gen_random_uuid(),
  review_title character varying,
  review_content text NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  is_verified boolean DEFAULT false,
  is_public boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  course_id uuid NOT NULL,
  CONSTRAINT course_reviews_pkey PRIMARY KEY (review_id),
  CONSTRAINT course_reviews_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT course_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text,
  category character varying NOT NULL DEFAULT 'ia'::character varying,
  level character varying NOT NULL DEFAULT 'beginner'::character varying CHECK (level::text = ANY (ARRAY['beginner'::character varying::text, 'intermediate'::character varying::text, 'advanced'::character varying::text])),
  instructor_id uuid,
  duration_total_minutes integer DEFAULT 0 CHECK (duration_total_minutes >= 0),
  thumbnail_url text,
  slug character varying NOT NULL UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  price numeric DEFAULT 0.00,
  average_rating numeric DEFAULT 0.00,
  student_count integer DEFAULT 0,
  review_count integer DEFAULT 0,
  learning_objectives jsonb DEFAULT '[]'::jsonb,
  approval_status character varying DEFAULT 'pending'::character varying CHECK (approval_status::text = ANY (ARRAY['pending'::character varying::text, 'approved'::character varying::text, 'rejected'::character varying::text])),
  approved_by uuid,
  approved_at timestamp with time zone,
  rejection_reason text,
  CONSTRAINT courses_pkey PRIMARY KEY (id),
  CONSTRAINT courses_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT fk_courses_instructor FOREIGN KEY (instructor_id) REFERENCES public.users(id)
);
CREATE TABLE public.daily_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  progress_date date NOT NULL,
  sessions_completed integer DEFAULT 0,
  sessions_missed integer DEFAULT 0,
  study_minutes integer DEFAULT 0,
  had_activity boolean DEFAULT false,
  streak_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT daily_progress_pkey PRIMARY KEY (id),
  CONSTRAINT daily_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT daily_progress_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.dashboard_layouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name character varying NOT NULL,
  layout_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_default boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT dashboard_layouts_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_layouts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.forbidden_words (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  word text NOT NULL UNIQUE,
  severity text NOT NULL DEFAULT 'medium'::text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  category text NOT NULL DEFAULT 'general'::text CHECK (category = ANY (ARRAY['insult'::text, 'racism'::text, 'sexism'::text, 'violence'::text, 'scam'::text, 'spam'::text, 'general'::text])),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT forbidden_words_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hierarchy_chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chat_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  content text NOT NULL,
  message_type character varying DEFAULT 'text'::character varying CHECK (message_type::text = ANY (ARRAY['text'::character varying, 'system'::character varying, 'file'::character varying]::text[])),
  metadata jsonb DEFAULT '{}'::jsonb,
  is_edited boolean DEFAULT false,
  is_deleted boolean DEFAULT false,
  edited_at timestamp with time zone,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hierarchy_chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT hierarchy_chat_messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.hierarchy_chats(id),
  CONSTRAINT hierarchy_chat_messages_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT hierarchy_chat_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id)
);
CREATE TABLE public.hierarchy_chat_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chat_id uuid NOT NULL,
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  is_active boolean DEFAULT true,
  joined_at timestamp with time zone DEFAULT now(),
  left_at timestamp with time zone,
  last_read_at timestamp with time zone,
  unread_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hierarchy_chat_participants_pkey PRIMARY KEY (id),
  CONSTRAINT hierarchy_chat_participants_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.hierarchy_chats(id),
  CONSTRAINT hierarchy_chat_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT hierarchy_chat_participants_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.hierarchy_chats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  chat_type character varying NOT NULL CHECK (chat_type::text = ANY (ARRAY['horizontal'::character varying, 'vertical'::character varying]::text[])),
  entity_type character varying NOT NULL CHECK (entity_type::text = ANY (ARRAY['region'::character varying, 'zone'::character varying, 'team'::character varying, 'node'::character varying]::text[])),
  entity_id uuid NOT NULL,
  level_role character varying,
  name character varying,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_message_at timestamp with time zone,
  CONSTRAINT hierarchy_chats_pkey PRIMARY KEY (id),
  CONSTRAINT hierarchy_chats_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.hierarchy_course_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  course_id uuid NOT NULL,
  assigned_by uuid NOT NULL,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  due_date timestamp with time zone,
  start_date timestamp with time zone,
  approach character varying CHECK (approach::text = ANY (ARRAY['fast'::character varying, 'balanced'::character varying, 'long'::character varying, 'custom'::character varying]::text[])),
  message text,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  total_users integer DEFAULT 0,
  assigned_users_count integer DEFAULT 0,
  completed_users_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hierarchy_course_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT hierarchy_course_assignments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT hierarchy_course_assignments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT hierarchy_course_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id)
);
CREATE TABLE public.lesson_activities (
  activity_id uuid NOT NULL DEFAULT gen_random_uuid(),
  activity_title character varying NOT NULL,
  activity_description text,
  activity_type character varying NOT NULL CHECK (activity_type::text = ANY (ARRAY['reflection'::character varying::text, 'exercise'::character varying::text, 'quiz'::character varying::text, 'discussion'::character varying::text, 'ai_chat'::character varying::text])),
  activity_content text NOT NULL,
  ai_prompts text,
  activity_order_index integer NOT NULL DEFAULT 1 CHECK (activity_order_index > 0),
  is_required boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  lesson_id uuid NOT NULL,
  estimated_time_minutes integer,
  CONSTRAINT lesson_activities_pkey PRIMARY KEY (activity_id),
  CONSTRAINT lesson_activities_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(lesson_id)
);
CREATE TABLE public.lesson_checkpoints (
  checkpoint_id uuid NOT NULL DEFAULT gen_random_uuid(),
  checkpoint_time_seconds integer NOT NULL CHECK (checkpoint_time_seconds >= 0),
  checkpoint_label character varying,
  checkpoint_description text,
  is_required_completion boolean DEFAULT false,
  checkpoint_order_index integer DEFAULT 1 CHECK (checkpoint_order_index > 0),
  created_at timestamp with time zone DEFAULT now(),
  lesson_id uuid NOT NULL,
  CONSTRAINT lesson_checkpoints_pkey PRIMARY KEY (checkpoint_id),
  CONSTRAINT lesson_checkpoints_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(lesson_id)
);
CREATE TABLE public.lesson_feedback (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lesson_id uuid NOT NULL,
  user_id uuid NOT NULL,
  feedback_type character varying NOT NULL CHECK (feedback_type::text = ANY (ARRAY['like'::character varying::text, 'dislike'::character varying::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT lesson_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT lesson_feedback_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(lesson_id),
  CONSTRAINT lesson_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT lesson_feedback_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.lesson_materials (
  material_id uuid NOT NULL DEFAULT gen_random_uuid(),
  material_title character varying NOT NULL,
  material_description text,
  material_type character varying NOT NULL CHECK (material_type::text = ANY (ARRAY['pdf'::character varying::text, 'link'::character varying::text, 'document'::character varying::text, 'quiz'::character varying::text, 'exercise'::character varying::text, 'reading'::character varying::text])),
  file_url text,
  external_url text,
  content_data jsonb,
  material_order_index integer DEFAULT 1 CHECK (material_order_index > 0),
  is_downloadable boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  lesson_id uuid NOT NULL,
  estimated_time_minutes integer,
  CONSTRAINT lesson_materials_pkey PRIMARY KEY (material_id),
  CONSTRAINT lesson_materials_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(lesson_id)
);
CREATE TABLE public.lesson_time_estimates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lesson_id uuid NOT NULL UNIQUE,
  video_duration_seconds integer DEFAULT 0,
  video_minutes numeric DEFAULT round(((video_duration_seconds)::numeric / 60.0), 2),
  activities_time_minutes numeric DEFAULT 0,
  reading_time_minutes numeric DEFAULT 0,
  quiz_time_minutes numeric DEFAULT 0,
  exercise_time_minutes numeric DEFAULT 0,
  link_time_minutes numeric DEFAULT 0,
  interactions_time_minutes numeric DEFAULT 3,
  total_time_minutes numeric DEFAULT round(((((((((video_duration_seconds)::numeric / 60.0) + COALESCE(activities_time_minutes, (0)::numeric)) + COALESCE(reading_time_minutes, (0)::numeric)) + COALESCE(quiz_time_minutes, (0)::numeric)) + COALESCE(exercise_time_minutes, (0)::numeric)) + COALESCE(link_time_minutes, (0)::numeric)) + COALESCE(interactions_time_minutes, (3)::numeric)), 2),
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lesson_time_estimates_pkey PRIMARY KEY (id),
  CONSTRAINT lesson_time_estimates_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(lesson_id)
);
CREATE TABLE public.lesson_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  session_id uuid,
  plan_id uuid,
  status text NOT NULL DEFAULT 'not_started'::text CHECK (status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'completed'::text])),
  started_at timestamp with time zone,
  start_trigger text CHECK (start_trigger = ANY (ARRAY['video_play'::text, 'page_load'::text, 'manual'::text])),
  video_started_at timestamp with time zone,
  video_ended_at timestamp with time zone,
  lia_first_message_at timestamp with time zone,
  lia_last_message_at timestamp with time zone,
  post_content_start_at timestamp with time zone,
  last_activity_at timestamp with time zone,
  next_analysis_at timestamp with time zone,
  completed_at timestamp with time zone,
  end_trigger text CHECK (end_trigger = ANY (ARRAY['quiz_submitted'::text, 'lia_inactivity_5m'::text, 'activity_inactivity_5m'::text, 'context_changed'::text, 'manual'::text])),
  t_lesson_minutes numeric,
  t_video_minutes numeric,
  t_materials_minutes numeric,
  t_restante_minutes numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  organization_id uuid,
  video_checkpoint_seconds integer DEFAULT 0,
  video_max_seconds integer DEFAULT 0,
  video_total_duration_seconds integer DEFAULT 0,
  video_playback_rate numeric DEFAULT 1.0,
  CONSTRAINT lesson_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT lesson_tracking_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(lesson_id),
  CONSTRAINT lesson_tracking_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.study_plans(id),
  CONSTRAINT lesson_tracking_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.study_sessions(id),
  CONSTRAINT lesson_tracking_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT lesson_tracking_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.lia_activity_completions (
  completion_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid NOT NULL,
  user_id uuid NOT NULL,
  activity_id uuid NOT NULL,
  status character varying NOT NULL,
  total_steps integer,
  completed_steps integer DEFAULT 0,
  current_step integer DEFAULT 1,
  generated_output jsonb,
  attempts_to_complete integer DEFAULT 1,
  time_to_complete_seconds integer,
  user_needed_help boolean DEFAULT false,
  lia_had_to_redirect integer DEFAULT 0,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT lia_activity_completions_pkey PRIMARY KEY (completion_id),
  CONSTRAINT lia_activity_completions_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.lesson_activities(activity_id),
  CONSTRAINT lia_activity_completions_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.lia_conversations(conversation_id),
  CONSTRAINT lia_activity_completions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT lia_activity_completions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.lia_common_questions (
  question_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  question_text text NOT NULL,
  context_type character varying,
  lesson_id uuid,
  activity_id uuid,
  times_asked integer DEFAULT 1,
  first_asked_at timestamp with time zone DEFAULT now(),
  last_asked_at timestamp with time zone DEFAULT now(),
  best_response text,
  best_response_rating numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lia_common_questions_pkey PRIMARY KEY (question_id),
  CONSTRAINT lia_common_questions_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.lesson_activities(activity_id),
  CONSTRAINT lia_common_questions_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(lesson_id)
);
CREATE TABLE public.lia_conversations (
  conversation_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  context_type character varying NOT NULL,
  course_id uuid,
  module_id uuid,
  lesson_id uuid,
  activity_id uuid,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  ended_at timestamp with time zone,
  duration_seconds integer,
  total_messages integer DEFAULT 0,
  total_user_messages integer DEFAULT 0,
  total_lia_messages integer DEFAULT 0,
  conversation_completed boolean DEFAULT false,
  user_abandoned boolean DEFAULT false,
  device_type character varying,
  browser character varying,
  ip_address inet,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  conversation_title character varying,
  organization_id uuid,
  CONSTRAINT lia_conversations_pkey PRIMARY KEY (conversation_id),
  CONSTRAINT lia_conversations_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.lesson_activities(activity_id),
  CONSTRAINT lia_conversations_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT lia_conversations_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(lesson_id),
  CONSTRAINT lia_conversations_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.course_modules(module_id),
  CONSTRAINT lia_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT lia_conversations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.lia_messages (
  message_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid NOT NULL,
  role character varying NOT NULL,
  content text NOT NULL,
  is_system_message boolean DEFAULT false,
  message_sequence integer NOT NULL,
  model_used character varying,
  tokens_used integer,
  cost_usd numeric,
  response_time_ms integer,
  user_sentiment character varying,
  sentiment_score numeric,
  contains_question boolean DEFAULT false,
  is_off_topic boolean DEFAULT false,
  lia_redirected boolean DEFAULT false,
  lia_provided_example boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lia_messages_pkey PRIMARY KEY (message_id),
  CONSTRAINT lia_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.lia_conversations(conversation_id)
);
CREATE TABLE public.lia_messages_tokens_tmp (
  message_id uuid NOT NULL,
  conversation_id uuid,
  role character varying,
  content text,
  is_system_message boolean,
  message_sequence integer,
  model_used character varying,
  tokens_used integer,
  cost_usd numeric,
  response_time_ms integer,
  user_sentiment character varying,
  sentiment_score numeric,
  contains_question boolean,
  is_off_topic boolean,
  lia_redirected boolean,
  lia_provided_example boolean,
  created_at timestamp with time zone,
  CONSTRAINT lia_messages_tokens_tmp_pkey PRIMARY KEY (message_id)
);
CREATE TABLE public.lia_personalization_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  base_style text DEFAULT 'professional'::text CHECK (base_style = ANY (ARRAY['professional'::text, 'casual'::text, 'technical'::text, 'friendly'::text, 'formal'::text])),
  is_friendly boolean DEFAULT true,
  is_enthusiastic boolean DEFAULT true,
  custom_instructions text,
  nickname text,
  voice_enabled boolean DEFAULT true,
  dictation_enabled boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lia_personalization_settings_pkey PRIMARY KEY (id),
  CONSTRAINT lia_personalization_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.lia_user_feedback (
  feedback_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  message_id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  user_id uuid NOT NULL,
  feedback_type character varying NOT NULL,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text,
  response_too_long boolean DEFAULT false,
  response_too_short boolean DEFAULT false,
  response_off_topic boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lia_user_feedback_pkey PRIMARY KEY (feedback_id),
  CONSTRAINT lia_user_feedback_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.lia_conversations(conversation_id),
  CONSTRAINT lia_user_feedback_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.lia_messages(message_id),
  CONSTRAINT lia_user_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.niveles (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  slug text NOT NULL UNIQUE,
  nombre text NOT NULL,
  CONSTRAINT niveles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_email_queue (
  queue_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  notification_id uuid,
  email_type character varying NOT NULL DEFAULT 'immediate'::character varying,
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['critical'::character varying::text, 'high'::character varying::text, 'medium'::character varying::text, 'low'::character varying::text])),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'processing'::character varying::text, 'sent'::character varying::text, 'failed'::character varying::text])),
  attempts integer DEFAULT 0,
  scheduled_at timestamp with time zone DEFAULT now(),
  sent_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_email_queue_pkey PRIMARY KEY (queue_id),
  CONSTRAINT notification_email_queue_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.user_notifications(notification_id),
  CONSTRAINT notification_email_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.notification_push_subscriptions (
  subscription_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  endpoint text NOT NULL,
  keys jsonb NOT NULL,
  user_agent text,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying::text, 'expired'::character varying::text, 'invalid'::character varying::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone,
  CONSTRAINT notification_push_subscriptions_pkey PRIMARY KEY (subscription_id),
  CONSTRAINT notification_push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.notification_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  event_type character varying NOT NULL,
  enabled boolean DEFAULT true,
  channels jsonb DEFAULT '["email"]'::jsonb,
  template text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT notification_settings_pkey PRIMARY KEY (id),
  CONSTRAINT notification_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.notification_stats (
  stat_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  organization_id uuid,
  notification_type character varying,
  stat_date date NOT NULL DEFAULT CURRENT_DATE,
  sent_count integer DEFAULT 0,
  read_count integer DEFAULT 0,
  action_taken_count integer DEFAULT 0,
  avg_read_time_seconds integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_stats_pkey PRIMARY KEY (stat_id),
  CONSTRAINT notification_stats_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT notification_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.oauth_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider character varying NOT NULL,
  provider_account_id character varying NOT NULL,
  access_token text,
  refresh_token text,
  token_expires_at timestamp without time zone,
  scope text,
  token_type character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT oauth_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT fk_oauth_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT oauth_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.organization_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  date date NOT NULL,
  total_users integer DEFAULT 0,
  active_users integer DEFAULT 0,
  courses_assigned integer DEFAULT 0,
  courses_completed integer DEFAULT 0,
  average_completion_rate numeric DEFAULT 0,
  total_learning_hours numeric DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT organization_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT organization_analytics_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organization_course_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  course_id uuid NOT NULL,
  assigned_by uuid,
  assigned_at timestamp without time zone DEFAULT now(),
  due_date timestamp without time zone,
  status character varying DEFAULT 'assigned'::character varying CHECK (status::text = ANY (ARRAY['assigned'::character varying::text, 'in_progress'::character varying::text, 'completed'::character varying::text, 'overdue'::character varying::text, 'cancelled'::character varying::text])),
  completion_percentage integer DEFAULT 0 CHECK (completion_percentage >= 0 AND completion_percentage <= 100),
  completed_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  message text,
  start_date timestamp without time zone,
  approach character varying CHECK (approach IS NULL OR (approach::text = ANY (ARRAY['fast'::character varying::text, 'balanced'::character varying::text, 'long'::character varying::text, 'custom'::character varying::text]))),
  hierarchy_assignment_id uuid,
  CONSTRAINT organization_course_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT organization_course_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id),
  CONSTRAINT organization_course_assignments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT organization_course_assignments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_course_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT organization_course_assignments_hierarchy_assignment_id_fkey FOREIGN KEY (hierarchy_assignment_id) REFERENCES public.hierarchy_course_assignments(id)
);
CREATE TABLE public.organization_course_purchases (
  purchase_id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  course_id uuid NOT NULL,
  purchased_by uuid NOT NULL,
  transaction_id uuid,
  payment_method_id uuid,
  original_price_cents integer NOT NULL CHECK (original_price_cents >= 0),
  discounted_price_cents integer NOT NULL CHECK (discounted_price_cents >= 0),
  final_price_cents integer NOT NULL CHECK (final_price_cents >= 0),
  discount_type character varying CHECK (discount_type IS NULL OR (discount_type::text = ANY (ARRAY['percentage'::character varying::text, 'fixed_amount'::character varying::text]))),
  discount_value numeric CHECK (discount_value IS NULL OR discount_value >= 0::numeric),
  discount_cents integer DEFAULT 0 CHECK (discount_cents >= 0),
  currency character varying NOT NULL DEFAULT 'USD'::character varying CHECK (currency::text = upper(currency::text)),
  access_status character varying NOT NULL DEFAULT 'active'::character varying CHECK (access_status::text = ANY (ARRAY['active'::character varying::text, 'suspended'::character varying::text, 'expired'::character varying::text, 'cancelled'::character varying::text])),
  purchased_at timestamp with time zone NOT NULL DEFAULT now(),
  access_granted_at timestamp with time zone,
  expires_at timestamp with time zone,
  billing_month date NOT NULL,
  billing_year integer NOT NULL,
  billing_month_number integer NOT NULL CHECK (billing_month_number >= 1 AND billing_month_number <= 12),
  purchase_method character varying CHECK (purchase_method IS NULL OR (purchase_method::text = ANY (ARRAY['subscription_benefit'::character varying::text, 'direct_purchase'::character varying::text, 'gift'::character varying::text]))),
  purchase_notes text,
  internal_notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_course_purchases_pkey PRIMARY KEY (purchase_id),
  CONSTRAINT organization_course_purchases_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT organization_course_purchases_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_course_purchases_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(payment_method_id),
  CONSTRAINT organization_course_purchases_purchased_by_fkey FOREIGN KEY (purchased_by) REFERENCES public.users(id),
  CONSTRAINT organization_course_purchases_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(transaction_id)
);
CREATE TABLE public.organization_node_courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  node_id uuid NOT NULL,
  course_id uuid NOT NULL,
  assigned_by uuid,
  status text DEFAULT 'active'::text,
  assigned_at timestamp with time zone DEFAULT now(),
  due_date timestamp with time zone,
  message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT organization_node_courses_pkey PRIMARY KEY (id),
  CONSTRAINT organization_node_courses_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.organization_nodes(id),
  CONSTRAINT organization_node_courses_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.organization_node_objectives (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  node_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  metric_type text NOT NULL,
  target_value numeric NOT NULL,
  current_value numeric DEFAULT 0,
  status text DEFAULT 'pending'::text,
  deadline timestamp with time zone,
  course_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_node_objectives_pkey PRIMARY KEY (id),
  CONSTRAINT organization_node_objectives_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.organization_nodes(id)
);
CREATE TABLE public.organization_node_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  node_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'member'::text,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_node_users_pkey PRIMARY KEY (id),
  CONSTRAINT organization_node_users_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.organization_nodes(id),
  CONSTRAINT organization_node_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.organization_nodes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  structure_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  parent_id uuid,
  name text NOT NULL,
  type text NOT NULL,
  code text,
  manager_id uuid,
  properties jsonb DEFAULT '{}'::jsonb,
  path USER-DEFINED,
  depth integer DEFAULT 0,
  position integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_nodes_pkey PRIMARY KEY (id),
  CONSTRAINT organization_nodes_structure_id_fkey FOREIGN KEY (structure_id) REFERENCES public.organization_structures(id),
  CONSTRAINT organization_nodes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_nodes_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.organization_nodes(id),
  CONSTRAINT organization_nodes_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.users(id)
);
CREATE TABLE public.organization_notification_preferences (
  preference_id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  event_type character varying NOT NULL,
  enabled boolean DEFAULT true,
  channels jsonb DEFAULT '["email"]'::jsonb,
  template text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_notification_preferences_pkey PRIMARY KEY (preference_id),
  CONSTRAINT organization_notification_preferences_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organization_regions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  code character varying,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  address text,
  city character varying,
  state character varying,
  country character varying DEFAULT 'México'::character varying,
  postal_code character varying,
  latitude numeric,
  longitude numeric,
  phone character varying,
  email character varying,
  manager_id uuid,
  logo_url text,
  banner_url text,
  CONSTRAINT organization_regions_pkey PRIMARY KEY (id),
  CONSTRAINT organization_regions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_regions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT organization_regions_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.users(id)
);
CREATE TABLE public.organization_structures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_structures_pkey PRIMARY KEY (id),
  CONSTRAINT organization_structures_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organization_teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  zone_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  code character varying,
  max_members integer CHECK (max_members IS NULL OR max_members > 0),
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  address text,
  city character varying,
  state character varying,
  country character varying DEFAULT 'México'::character varying,
  postal_code character varying,
  latitude numeric,
  longitude numeric,
  phone character varying,
  email character varying,
  leader_id uuid,
  target_goal text,
  monthly_target numeric,
  logo_url text,
  banner_url text,
  CONSTRAINT organization_teams_pkey PRIMARY KEY (id),
  CONSTRAINT organization_teams_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_teams_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.organization_zones(id),
  CONSTRAINT organization_teams_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT organization_teams_leader_id_fkey FOREIGN KEY (leader_id) REFERENCES public.users(id)
);
CREATE TABLE public.organization_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['owner'::character varying::text, 'admin'::character varying::text, 'member'::character varying::text])),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying::text, 'invited'::character varying::text, 'suspended'::character varying::text, 'removed'::character varying::text])),
  invited_by uuid,
  invited_at timestamp without time zone,
  joined_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  job_title text,
  team_id uuid,
  zone_id uuid,
  region_id uuid,
  hierarchy_scope character varying DEFAULT NULL::character varying CHECK (hierarchy_scope IS NULL OR (hierarchy_scope::text = ANY (ARRAY['organization'::text, 'region'::text, 'zone'::text, 'team'::text]))),
  CONSTRAINT organization_users_pkey PRIMARY KEY (id),
  CONSTRAINT organization_users_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id),
  CONSTRAINT organization_users_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT organization_users_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.organization_teams(id),
  CONSTRAINT organization_users_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.organization_zones(id),
  CONSTRAINT organization_users_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.organization_regions(id)
);
CREATE TABLE public.organization_zones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  region_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  code character varying,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  address text,
  city character varying,
  state character varying,
  country character varying DEFAULT 'México'::character varying,
  postal_code character varying,
  latitude numeric,
  longitude numeric,
  phone character varying,
  email character varying,
  manager_id uuid,
  logo_url text,
  banner_url text,
  CONSTRAINT organization_zones_pkey PRIMARY KEY (id),
  CONSTRAINT organization_zones_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_zones_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.organization_regions(id),
  CONSTRAINT organization_zones_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT organization_zones_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  contact_email character varying,
  contact_phone character varying,
  website_url text,
  logo_url text,
  subscription_plan character varying DEFAULT 'team'::character varying CHECK (subscription_plan::text = ANY (ARRAY['team'::character varying::text, 'business'::character varying::text, 'enterprise'::character varying::text])),
  subscription_status character varying DEFAULT 'active'::character varying CHECK (subscription_status::text = ANY (ARRAY['active'::character varying::text, 'expired'::character varying::text, 'cancelled'::character varying::text, 'trial'::character varying::text, 'pending'::character varying::text])),
  subscription_start_date timestamp without time zone,
  subscription_end_date timestamp without time zone,
  max_users integer DEFAULT 10,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  brand_color_primary character varying DEFAULT '#3b82f6'::character varying,
  brand_color_secondary character varying DEFAULT '#10b981'::character varying,
  brand_color_accent character varying DEFAULT '#8b5cf6'::character varying,
  brand_font_family character varying DEFAULT 'Inter'::character varying,
  brand_logo_url text,
  brand_favicon_url text,
  slug character varying NOT NULL UNIQUE,
  panel_styles jsonb,
  user_dashboard_styles jsonb,
  login_styles jsonb,
  selected_theme character varying DEFAULT NULL::character varying,
  billing_cycle character varying CHECK (billing_cycle IS NULL OR (billing_cycle::text = ANY (ARRAY['monthly'::character varying::text, 'yearly'::character varying::text]))),
  brand_banner_url text,
  google_login_enabled boolean DEFAULT false,
  microsoft_login_enabled boolean DEFAULT false,
  show_navbar_name boolean DEFAULT true,
  hierarchy_enabled boolean DEFAULT false,
  hierarchy_config jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.password_reset_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  token character varying NOT NULL UNIQUE,
  expires_at timestamp without time zone NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  used_at timestamp without time zone,
  CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payment_methods (
  payment_method_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_method_type character varying NOT NULL CHECK (payment_method_type::text = ANY (ARRAY['credit_card'::character varying::text, 'debit_card'::character varying::text, 'paypal'::character varying::text, 'bank_transfer'::character varying::text, 'crypto'::character varying::text])),
  payment_method_name character varying NOT NULL,
  encrypted_data jsonb NOT NULL,
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT payment_methods_pkey PRIMARY KEY (payment_method_id),
  CONSTRAINT payment_methods_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.preguntas (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  codigo text,
  section text,
  bloque text,
  area_id integer,
  exclusivo_rol_id integer,
  texto text NOT NULL,
  tipo text NOT NULL,
  opciones jsonb,
  locale text,
  peso numeric,
  escala jsonb,
  scoring jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  respuesta_correcta text,
  dimension jsonb,
  exclusivo_nivel_id integer,
  dificultad integer CHECK (dificultad IS NULL OR dificultad >= 1 AND dificultad <= 5),
  CONSTRAINT preguntas_pkey PRIMARY KEY (id),
  CONSTRAINT preguntas_exclusivo_nivel_id_fkey FOREIGN KEY (exclusivo_nivel_id) REFERENCES public.niveles(id),
  CONSTRAINT preguntas_exclusivo_rol_id_fkey FOREIGN KEY (exclusivo_rol_id) REFERENCES public.roles(id)
);
CREATE TABLE public.refresh_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone DEFAULT now(),
  device_fingerprint text,
  ip_address text,
  user_agent text,
  is_revoked boolean DEFAULT false,
  revoked_at timestamp with time zone,
  revoked_reason text,
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.region_course_assignments (
  hierarchy_assignment_id uuid NOT NULL,
  region_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT region_course_assignments_pkey PRIMARY KEY (hierarchy_assignment_id),
  CONSTRAINT region_course_assignments_hierarchy_assignment_id_fkey FOREIGN KEY (hierarchy_assignment_id) REFERENCES public.hierarchy_course_assignments(id),
  CONSTRAINT region_course_assignments_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.organization_regions(id)
);
CREATE TABLE public.relaciones (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  slug text NOT NULL UNIQUE,
  nombre text NOT NULL,
  CONSTRAINT relaciones_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reportes_problemas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  titulo character varying NOT NULL,
  descripcion text NOT NULL,
  categoria character varying NOT NULL CHECK (categoria::text = ANY (ARRAY['bug'::character varying::text, 'sugerencia'::character varying::text, 'contenido'::character varying::text, 'performance'::character varying::text, 'ui-ux'::character varying::text, 'otro'::character varying::text])),
  prioridad character varying DEFAULT 'media'::character varying CHECK (prioridad::text = ANY (ARRAY['baja'::character varying::text, 'media'::character varying::text, 'alta'::character varying::text, 'critica'::character varying::text])),
  pagina_url text NOT NULL,
  pathname character varying,
  user_agent text,
  screen_resolution character varying,
  navegador character varying,
  screenshot_url text,
  pasos_reproducir text,
  comportamiento_esperado text,
  estado character varying DEFAULT 'pendiente'::character varying CHECK (estado::text = ANY (ARRAY['pendiente'::character varying::text, 'en_revision'::character varying::text, 'en_progreso'::character varying::text, 'resuelto'::character varying::text, 'rechazado'::character varying::text, 'duplicado'::character varying::text])),
  admin_asignado uuid,
  notas_admin text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  resuelto_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  session_recording text,
  recording_size character varying,
  recording_duration integer,
  CONSTRAINT reportes_problemas_pkey PRIMARY KEY (id),
  CONSTRAINT reportes_problemas_admin_asignado_fkey FOREIGN KEY (admin_asignado) REFERENCES public.users(id),
  CONSTRAINT reportes_problemas_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.roles (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  slug text NOT NULL UNIQUE,
  nombre text NOT NULL,
  area_id integer,
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.scorm_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  package_id uuid NOT NULL,
  attempt_number integer DEFAULT 1,
  lesson_status character varying DEFAULT 'not attempted'::character varying,
  lesson_location text,
  credit character varying DEFAULT 'credit'::character varying,
  entry character varying DEFAULT 'ab-initio'::character varying,
  exit_type character varying,
  score_raw numeric,
  score_min numeric DEFAULT 0,
  score_max numeric DEFAULT 100,
  score_scaled numeric,
  total_time interval DEFAULT '00:00:00'::interval,
  session_time interval DEFAULT '00:00:00'::interval,
  suspend_data text,
  started_at timestamp with time zone DEFAULT now(),
  last_accessed_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT scorm_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT scorm_attempts_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.scorm_packages(id),
  CONSTRAINT scorm_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.scorm_interactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  attempt_id uuid,
  interaction_id character varying NOT NULL,
  interaction_type character varying,
  description text,
  learner_response text,
  correct_response text,
  result character varying,
  weighting numeric DEFAULT 1,
  latency interval,
  timestamp timestamp with time zone DEFAULT now(),
  CONSTRAINT scorm_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT scorm_interactions_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES public.scorm_attempts(id)
);
CREATE TABLE public.scorm_objectives (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  attempt_id uuid,
  objective_id character varying NOT NULL,
  score_raw numeric,
  score_min numeric,
  score_max numeric,
  score_scaled numeric,
  success_status character varying,
  completion_status character varying,
  description text,
  CONSTRAINT scorm_objectives_pkey PRIMARY KEY (id),
  CONSTRAINT scorm_objectives_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES public.scorm_attempts(id)
);
CREATE TABLE public.scorm_packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  course_id uuid,
  title character varying NOT NULL,
  description text,
  version character varying DEFAULT 'SCORM_1.2'::character varying,
  manifest_data jsonb NOT NULL,
  entry_point text NOT NULL,
  storage_path text NOT NULL,
  file_size bigint,
  status character varying DEFAULT 'active'::character varying,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scorm_packages_pkey PRIMARY KEY (id),
  CONSTRAINT scorm_packages_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT scorm_packages_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT scorm_packages_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.sectores (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  slug text NOT NULL UNIQUE,
  nombre text NOT NULL,
  CONSTRAINT sectores_pkey PRIMARY KEY (id)
);
CREATE TABLE public.study_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  goal_hours_per_week numeric NOT NULL DEFAULT 5,
  start_date date,
  end_date date,
  timezone text NOT NULL DEFAULT 'UTC'::text,
  preferred_days ARRAY NOT NULL DEFAULT '{1,2,3,4,5}'::smallint[],
  preferred_time_blocks jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  generation_mode text DEFAULT 'manual'::text CHECK (generation_mode = ANY (ARRAY['manual'::text, 'ai_generated'::text])),
  ai_generation_metadata jsonb DEFAULT '{}'::jsonb,
  preferred_session_type text DEFAULT 'medium'::text CHECK (preferred_session_type = ANY (ARRAY['short'::text, 'medium'::text, 'long'::text])),
  min_study_minutes integer,
  min_rest_minutes integer,
  max_study_session_minutes integer,
  break_intervals jsonb DEFAULT '[]'::jsonb,
  min_session_minutes integer,
  max_session_minutes integer,
  break_duration_minutes integer,
  calendar_analyzed boolean DEFAULT false,
  calendar_provider text,
  lia_availability_analysis jsonb DEFAULT '{}'::jsonb,
  lia_time_analysis jsonb DEFAULT '{}'::jsonb,
  user_type text CHECK (user_type IS NULL OR (user_type = ANY (ARRAY['b2b'::text, 'b2c'::text]))),
  organization_id uuid,
  course_ids ARRAY DEFAULT '{}'::uuid[],
  CONSTRAINT study_plans_pkey PRIMARY KEY (id),
  CONSTRAINT study_plans_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT study_plans_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.study_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  timezone text NOT NULL DEFAULT 'UTC'::text,
  preferred_time_of_day text NOT NULL DEFAULT 'morning'::text,
  preferred_days ARRAY NOT NULL DEFAULT '{1,2,3,4,5}'::smallint[],
  daily_target_minutes integer NOT NULL DEFAULT 60,
  weekly_target_minutes integer NOT NULL DEFAULT 300,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  preferred_session_type text DEFAULT 'medium'::text CHECK (preferred_session_type = ANY (ARRAY['short'::text, 'medium'::text, 'long'::text])),
  min_session_minutes integer,
  max_session_minutes integer,
  break_duration_minutes integer,
  calendar_connected boolean DEFAULT false,
  calendar_provider text,
  CONSTRAINT study_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT study_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.study_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_id uuid,
  user_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  course_id text,
  focus_area text,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  duration_minutes integer,
  status text NOT NULL DEFAULT 'planned'::text,
  actual_duration_minutes integer,
  recurrence jsonb,
  metrics jsonb DEFAULT '{}'::jsonb,
  calendar_provider text,
  external_event_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lesson_id uuid,
  is_ai_generated boolean DEFAULT false,
  streak_day integer,
  lesson_min_time_minutes integer,
  session_type text DEFAULT 'medium'::text CHECK (session_type = ANY (ARRAY['short'::text, 'medium'::text, 'long'::text])),
  course_complexity jsonb DEFAULT '{}'::jsonb,
  completed_at timestamp with time zone,
  notes text,
  self_evaluation integer CHECK (self_evaluation IS NULL OR self_evaluation >= 1 AND self_evaluation <= 5),
  was_rescheduled boolean DEFAULT false,
  rescheduled_from timestamp with time zone,
  break_duration_minutes integer,
  calendar_conflict_checked boolean DEFAULT false,
  lia_suggested boolean DEFAULT false,
  due_date timestamp with time zone,
  calendar_synced_at timestamp with time zone,
  started_at timestamp with time zone,
  completion_method text CHECK (completion_method IS NULL OR (completion_method = ANY (ARRAY['quiz'::text, 'lia_inactivity'::text, 'activity_inactivity'::text, 'context_changed'::text, 'manual'::text]))),
  organization_id uuid,
  CONSTRAINT study_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT study_sessions_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(lesson_id),
  CONSTRAINT study_sessions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.study_plans(id),
  CONSTRAINT study_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT study_sessions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.subscriptions (
  subscription_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_type character varying NOT NULL CHECK (subscription_type::text = ANY (ARRAY['monthly'::character varying::text, 'yearly'::character varying::text, 'lifetime'::character varying::text, 'course_access'::character varying::text])),
  subscription_status character varying DEFAULT 'active'::character varying CHECK (subscription_status::text = ANY (ARRAY['active'::character varying::text, 'paused'::character varying::text, 'cancelled'::character varying::text, 'expired'::character varying::text])),
  price_cents integer NOT NULL CHECK (price_cents > 0),
  start_date timestamp with time zone DEFAULT now(),
  end_date timestamp with time zone,
  next_billing_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  course_id uuid,
  plan_id character varying CHECK (plan_id IS NULL OR (plan_id::text = ANY (ARRAY['team'::character varying::text, 'business'::character varying::text, 'enterprise'::character varying::text]))),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (subscription_id),
  CONSTRAINT subscriptions_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.team_course_assignments (
  hierarchy_assignment_id uuid NOT NULL,
  team_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT team_course_assignments_pkey PRIMARY KEY (hierarchy_assignment_id),
  CONSTRAINT team_course_assignments_hierarchy_assignment_id_fkey FOREIGN KEY (hierarchy_assignment_id) REFERENCES public.hierarchy_course_assignments(id),
  CONSTRAINT team_course_assignments_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.organization_teams(id)
);
CREATE TABLE public.transactions (
  transaction_id uuid NOT NULL DEFAULT gen_random_uuid(),
  amount_cents integer NOT NULL CHECK (amount_cents > 0),
  currency character varying NOT NULL DEFAULT 'USD'::character varying,
  transaction_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (transaction_status::text = ANY (ARRAY['pending'::character varying::text, 'completed'::character varying::text, 'failed'::character varying::text, 'refunded'::character varying::text, 'cancelled'::character varying::text])),
  transaction_type character varying NOT NULL CHECK (transaction_type::text = ANY (ARRAY['course_purchase'::character varying::text, 'subscription'::character varying::text, 'refund'::character varying::text, 'credit'::character varying::text])),
  processor_transaction_id character varying,
  processor_response jsonb,
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  course_id uuid,
  payment_method_id uuid NOT NULL,
  CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id),
  CONSTRAINT transactions_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT transactions_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(payment_method_id),
  CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_activity_log (
  log_id uuid NOT NULL DEFAULT gen_random_uuid(),
  action_type character varying NOT NULL CHECK (action_type::text = ANY (ARRAY['course_view'::character varying::text, 'lesson_start'::character varying::text, 'lesson_complete'::character varying::text, 'video_play'::character varying::text, 'video_pause'::character varying::text, 'video_seek'::character varying::text, 'activity_complete'::character varying::text, 'note_create'::character varying::text, 'note_update'::character varying::text])),
  action_description text,
  session_id uuid,
  user_agent text,
  ip_address inet,
  action_timestamp timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  course_id uuid,
  lesson_id uuid,
  organization_id uuid,
  CONSTRAINT user_activity_log_pkey PRIMARY KEY (log_id),
  CONSTRAINT user_activity_log_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT user_activity_log_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(lesson_id),
  CONSTRAINT user_activity_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_activity_log_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_calendar_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  location text,
  is_all_day boolean DEFAULT false,
  provider text DEFAULT 'local'::text,
  source text DEFAULT 'user_created'::text,
  google_event_id text,
  microsoft_event_id text,
  color text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_calendar_events_pkey PRIMARY KEY (id),
  CONSTRAINT user_calendar_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_course_certificates (
  certificate_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  course_id uuid NOT NULL,
  enrollment_id uuid NOT NULL,
  certificate_url text NOT NULL CHECK (length(btrim(certificate_url)) > 0),
  issued_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  certificate_hash character UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  template_id uuid,
  organization_id uuid,
  CONSTRAINT user_course_certificates_pkey PRIMARY KEY (certificate_id),
  CONSTRAINT user_course_certificates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_course_certificates_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT user_course_certificates_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.user_course_enrollments(enrollment_id),
  CONSTRAINT user_course_certificates_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.certificate_templates(id),
  CONSTRAINT user_course_certificates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_course_enrollments (
  enrollment_id uuid NOT NULL DEFAULT gen_random_uuid(),
  enrollment_status character varying DEFAULT 'active'::character varying CHECK (enrollment_status::text = ANY (ARRAY['active'::character varying::text, 'completed'::character varying::text, 'paused'::character varying::text, 'cancelled'::character varying::text])),
  overall_progress_percentage numeric DEFAULT 0.00 CHECK (overall_progress_percentage >= 0.00 AND overall_progress_percentage <= 100.00),
  enrolled_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  last_accessed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  course_id uuid NOT NULL,
  organization_id uuid,
  CONSTRAINT user_course_enrollments_pkey PRIMARY KEY (enrollment_id),
  CONSTRAINT user_course_enrollments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT user_course_enrollments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_course_enrollments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  token text NOT NULL UNIQUE,
  role text NOT NULL DEFAULT 'member'::text CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text])),
  organization_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'expired'::text, 'revoked'::text])),
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  accepted_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT user_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT user_invitations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT user_invitations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_lesson_notes (
  note_id uuid NOT NULL DEFAULT gen_random_uuid(),
  note_title character varying NOT NULL,
  note_content text NOT NULL,
  note_tags jsonb DEFAULT '[]'::jsonb,
  is_auto_generated boolean DEFAULT false,
  source_type character varying DEFAULT 'manual'::character varying CHECK (source_type::text = ANY (ARRAY['manual'::character varying::text, 'chat'::character varying::text, 'import'::character varying::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  organization_id uuid,
  CONSTRAINT user_lesson_notes_pkey PRIMARY KEY (note_id),
  CONSTRAINT user_lesson_notes_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(lesson_id),
  CONSTRAINT user_lesson_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_lesson_notes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_lesson_progress (
  progress_id uuid NOT NULL DEFAULT gen_random_uuid(),
  lesson_status character varying DEFAULT 'not_started'::character varying CHECK (lesson_status::text = ANY (ARRAY['not_started'::character varying::text, 'in_progress'::character varying::text, 'completed'::character varying::text, 'locked'::character varying::text])),
  video_progress_percentage numeric DEFAULT 0.00 CHECK (video_progress_percentage >= 0.00 AND video_progress_percentage <= 100.00),
  current_time_seconds integer DEFAULT 0 CHECK (current_time_seconds >= 0),
  is_completed boolean DEFAULT false,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  time_spent_minutes integer DEFAULT 0 CHECK (time_spent_minutes >= 0),
  last_accessed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  enrollment_id uuid NOT NULL,
  quiz_progress_percentage numeric DEFAULT 0.00 CHECK (quiz_progress_percentage >= 0.00 AND quiz_progress_percentage <= 100.00),
  quiz_completed boolean DEFAULT false,
  quiz_passed boolean DEFAULT false,
  organization_id uuid,
  CONSTRAINT user_lesson_progress_pkey PRIMARY KEY (progress_id),
  CONSTRAINT user_lesson_progress_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.user_course_enrollments(enrollment_id),
  CONSTRAINT user_lesson_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(lesson_id),
  CONSTRAINT user_lesson_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_lesson_progress_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_notification_preferences (
  preference_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  notification_type character varying NOT NULL,
  in_app_enabled boolean DEFAULT true,
  push_enabled boolean DEFAULT false,
  email_enabled boolean DEFAULT true,
  email_frequency character varying DEFAULT 'daily'::character varying CHECK (email_frequency::text = ANY (ARRAY['immediate'::character varying::text, 'daily'::character varying::text, 'weekly'::character varying::text, 'never'::character varying::text])),
  do_not_disturb_start time without time zone,
  do_not_disturb_end time without time zone,
  do_not_disturb_days jsonb DEFAULT '[]'::jsonb,
  timezone character varying DEFAULT 'UTC'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_notification_preferences_pkey PRIMARY KEY (preference_id),
  CONSTRAINT user_notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_notifications (
  notification_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  notification_type character varying NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['critical'::character varying::text, 'high'::character varying::text, 'medium'::character varying::text, 'low'::character varying::text])),
  status character varying DEFAULT 'unread'::character varying CHECK (status::text = ANY (ARRAY['unread'::character varying::text, 'read'::character varying::text, 'archived'::character varying::text])),
  channels_sent jsonb DEFAULT '[]'::jsonb,
  channels_pending jsonb DEFAULT '[]'::jsonb,
  read_at timestamp with time zone,
  expires_at timestamp with time zone,
  organization_id uuid,
  group_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_notifications_pkey PRIMARY KEY (notification_id),
  CONSTRAINT user_notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_perfil (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  cargo_titulo text,
  rol_id integer,
  nivel_id integer,
  area_id integer,
  relacion_id integer,
  tamano_id integer,
  sector_id integer,
  pais text,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  dificultad_id integer CHECK (dificultad_id IS NULL OR dificultad_id >= 1 AND dificultad_id <= 5),
  uso_ia_respuesta text,
  CONSTRAINT user_perfil_pkey PRIMARY KEY (id),
  CONSTRAINT user_perfil_nivel_id_fkey FOREIGN KEY (nivel_id) REFERENCES public.niveles(id),
  CONSTRAINT user_perfil_relacion_id_fkey FOREIGN KEY (relacion_id) REFERENCES public.relaciones(id),
  CONSTRAINT user_perfil_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES public.roles(id),
  CONSTRAINT user_perfil_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.sectores(id),
  CONSTRAINT user_perfil_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_quiz_submissions (
  submission_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_answers jsonb NOT NULL DEFAULT '{}'::jsonb,
  score integer DEFAULT 0 CHECK (score >= 0),
  total_points integer DEFAULT 0 CHECK (total_points >= 0),
  percentage_score numeric DEFAULT 0.00 CHECK (percentage_score >= 0.00 AND percentage_score <= 100.00),
  is_passed boolean DEFAULT false,
  completed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  enrollment_id uuid NOT NULL,
  material_id uuid,
  activity_id uuid,
  organization_id uuid,
  CONSTRAINT user_quiz_submissions_pkey PRIMARY KEY (submission_id),
  CONSTRAINT user_quiz_submissions_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.lesson_activities(activity_id),
  CONSTRAINT user_quiz_submissions_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(lesson_id),
  CONSTRAINT user_quiz_submissions_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.lesson_materials(material_id),
  CONSTRAINT user_quiz_submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_quiz_submissions_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.user_course_enrollments(enrollment_id),
  CONSTRAINT user_quiz_submissions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_session (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  jwt_id uuid,
  issued_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  ip inet,
  user_agent text,
  revoked boolean NOT NULL DEFAULT false,
  CONSTRAINT user_session_pkey PRIMARY KEY (id),
  CONSTRAINT user_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_streaks (
  user_id uuid NOT NULL,
  current_streak integer DEFAULT 0,
  longest_streak integer DEFAULT 0,
  last_session_date date,
  total_sessions_completed integer DEFAULT 0,
  total_study_minutes integer DEFAULT 0,
  total_sessions_missed integer DEFAULT 0,
  total_sessions_rescheduled integer DEFAULT 0,
  weekly_sessions_completed integer DEFAULT 0,
  weekly_study_minutes integer DEFAULT 0,
  week_start_date date,
  monthly_sessions_completed integer DEFAULT 0,
  monthly_study_minutes integer DEFAULT 0,
  month_start_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  CONSTRAINT user_streaks_pkey PRIMARY KEY (id),
  CONSTRAINT user_streaks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_streaks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_tour_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tour_id text NOT NULL,
  completed_at timestamp with time zone,
  skipped_at timestamp with time zone,
  step_reached integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_tour_progress_pkey PRIMARY KEY (id),
  CONSTRAINT user_tour_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_warnings (
  warning_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  reason text NOT NULL,
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['post'::text, 'comment'::text, 'other'::text])),
  content_id uuid,
  blocked_content text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_warnings_pkey PRIMARY KEY (warning_id),
  CONSTRAINT user_warnings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text NOT NULL UNIQUE CHECK (username ~* '^[A-Za-z0-9_-]+$'::text),
  email text UNIQUE CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'::text),
  password_hash text CHECK (password_hash IS NULL OR password_hash ~* '^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_login_at timestamp with time zone,
  cargo_rol text CHECK (cargo_rol = ANY (ARRAY['Usuario'::text, 'Instructor'::text, 'Administrador'::text, 'Business'::text, 'Business User'::text])),
  type_rol text,
  first_name text,
  last_name text,
  display_name text,
  phone character varying,
  bio text,
  location text,
  profile_picture_url text,
  email_verified boolean NOT NULL DEFAULT false,
  email_verified_at timestamp with time zone,
  country_code text,
  oauth_provider character varying,
  oauth_provider_id character varying,
  is_banned boolean NOT NULL DEFAULT false,
  banned_at timestamp with time zone,
  ban_reason text,
  signature_url text,
  signature_name text,
  notification_email boolean DEFAULT true,
  notification_push boolean DEFAULT true,
  notification_marketing boolean DEFAULT false,
  notification_course_updates boolean DEFAULT true,
  notification_community_updates boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.zone_course_assignments (
  hierarchy_assignment_id uuid NOT NULL,
  zone_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zone_course_assignments_pkey PRIMARY KEY (hierarchy_assignment_id),
  CONSTRAINT zone_course_assignments_hierarchy_assignment_id_fkey FOREIGN KEY (hierarchy_assignment_id) REFERENCES public.hierarchy_course_assignments(id),
  CONSTRAINT zone_course_assignments_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.organization_zones(id)
);